PYTHONPATH=. python main.py \
  --train_mode bayesian_hpo \
  --model_name svm \
  --num_epochs 1 \
  --learning_rate 0.1 \
  --batch_size 256 \
  --num_workers 2 \
  --num_outputs 10 \
  --num_trials 20 \
  --max_wallclock_time 3600 \
  --eta 2 \
  --min_number_of_epochs 10 \
  --max_number_of_epochs 100 \
  --prefact 1 \
  --alpha 0.0001 \
  --l1_ratio 0.15 \
  --C 1.0 \
  --gamma 0.001
